# ?????? ?? -> ???? 8080
server:
  port: 8080

#database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/연결할 DB명?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: MySQL 유저명
    password: 해당 유저 PW

# MyBatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  # DTO ??? (BoardDTO ?? ???)
  type-aliases-package: com.ykk.board.dto